config/routes.rb
Rails.application.routes.draw do
  # Sidekiq dashboard
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # Root index
  root 'index#view'
  # Login/logout pages
  devise_for :pets, controllers: { registrations: 'registrations' }
  # Custom redirects and routes
  get '/evelyn' => redirect("http://evelyn.pet")
  get '/naptime' => 'index#naptime'
  get '/pets' => 'index#view'
  # Pettings
  get '/pettings' => 'pet_interactions#index'
  post '/:url/petting'  => 'pet_interactions#do_a_petting'
  get '/:url/pettings' => 'pet_interactions#how_many_pettings'
  # Pet pages
  resources :pages, only: [:edit], param: :url
  # View pet pages at root URL
  resources :pages, path: '', only: [:show, :update], param: :url
end

app/controllers/pet_interactions_controller.rb
class PetInteractionsController < ApplicationController
  # Find appropriate records
  before_action :set_pet_interactions_for_pet, only: [:index]
  before_action :set_page_and_pet, only: [:do_a_petting, :how_many_pettings]
  # Verify legitimacy of incoming petting parameters
  before_action :not_too_many_pettings, only: [:do_a_petting]
  before_action :only_wanted_pettings, only: [:do_a_petting]
  # Set pet interaction
  before_action :set_pet_interaction, only: [:do_a_petting]


  def index; end

  def do_a_petting
    increment_pet_pettings(@pet, 'received', params[:this_many])
    if current_pet
      increment_pet_pettings(current_pet, 'performed', params[:this_many])
    end
    increment_total_pettings(@pet_interaction, params[:this_many])
    set_interaction_dates(@pet_interaction)
  end

  def how_many_pettings
    if params[:petter_id]
      pet_interaction = PetInteraction.find_by(petted_id: @pet.id, petter_id: params[:petter_id])
      petting_count = pet_interaction.total_pettings
    else
      petting_count = @pet.received_pettings_count
    end
    respond_to do |format|
      format.json { render json: { count: petting_count } }
    end
  end

  private

  def set_pet_interactions_for_pet
    @petters = PetInteraction.where("petted_id=?", current_pet.id)
    @petted = PetInteraction.where("petter_id=?", current_pet.id)
  end

  def set_pet_interaction
    if current_pet
      @pet_interaction = PetInteraction.find_or_create_by(petter_id: current_pet.id, petted_id: @pet.id)
    else
      @pet_interaction = PetInteraction.find_or_create_by(petter_id: false, petted_id: @pet.id)
    end
  end

  def set_page_and_pet
    params[:url].downcase!
    @page = Page.find_by! url: params[:url]
    @pet = @page.pet
  end

  def not_too_many_pettings
    if params[:this_many] && params[:this_many].to_i
      params[:this_many] = params[:this_many].to_i
    else
      params[:this_many] = 1
    end
    if params[:this_many] > 17
      # 18 is too many pettings
      render status: :too_many_requests, inline: '<img src="//http.cat/429">'
    end
    if params[:this_many] < 0
      # No negative petting!
      render status: :bad_request, inline: '<img src="//http.cat/400">'
    end
  end

  def only_wanted_pettings
    unless current_pet || @page.allow_anon_petting
      render status: :unauthorized, inline: '<img src="//http.cat/401">'
    end
  end

  def increment_pet_pettings(pet, counter_type, amount)
    if counter_type == 'performed'
      pet.increment(:performed_pettings_count, amount)
    else
      pet.increment(:received_pettings_count, amount)
    end
    pet.save!
  end

  def increment_total_pettings(pet_interaction, amount)
    pet_interaction.increment(:total_pettings, amount)
    pet_interaction.save!
  end

  def set_interaction_dates(pet_interaction)
    now = DateTime.now.utc
    if pet_interaction.first_petting.nil?
      pet_interaction.first_petting = now
    end
    if pet_interaction.last_petting.nil? or now > pet_interaction.last_petting
      pet_interaction.last_petting = now
    end
    pet_interaction.save!
  end
end

app/views/pet_interactions/_form.html.erb
<%= form_for(pet_interaction) do |f| %>
  <% if pet_interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet_interaction.errors.count, "error") %> prohibited this pet_interaction from being saved:</h2>

      <ul>
      <% pet_interaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :petter_id %>
    <%= f.number_field :petter_id %>
  </div>

  <div class="field">
    <%= f.label :petted_id %>
    <%= f.number_field :petted_id %>
  </div>

  <div class="field">
    <%= f.label :total_pettings %>
    <%= f.number_field :total_pettings %>
  </div>

  <div class="field">
    <%= f.label :first_petting %>
    <%= f.datetime_select :first_petting %>
  </div>

  <div class="field">
    <%= f.label :last_petting %>
    <%= f.datetime_select :last_petting %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pet_interactions/edit.html.erb
<h1>Editing Pet Interaction</h1>

<%= render 'form', pet_interaction: @pet_interaction %>

<%= link_to 'Show', @pet_interaction %> |
<%= link_to 'Back', pet_interactions_path %>

app/views/pet_interactions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
    <h1>Your petters</h1>

    <ul class="list-group">
      <% @petters.each do |petter| %>
          <li class="list-group-item">
            <% if petter.petter %>
                <%= link_to petter.petter_name, petter.petter_page_url %>
            <% else %>
                Anonymous
            <% end %>
            <span class="badge"><%= petter.total_pettings %></span>
          </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-6">
    <h1>Your petted pets</h1>
    <ul class="list-group">
      <% @petted.each do |petted| %>
          <li class="list-group-item">
            <%= link_to petted.petted_name, petted.petted_page_url %>
            <span class="badge"><%= petted.total_pettings %></span>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pet_interactions/new.html.erb
<h1>New Pet Interaction</h1>

<%= render 'form', pet_interaction: @pet_interaction %>

<%= link_to 'Back', pet_interactions_path %>

app/views/pet_interactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Petter:</strong>
  <%= @pet_interaction.petter_id %>
</p>

<p>
  <strong>Petted:</strong>
  <%= @pet_interaction.petted_id %>
</p>

<p>
  <strong>Total pettings:</strong>
  <%= @pet_interaction.total_pettings %>
</p>

<p>
  <strong>First petting:</strong>
  <%= @pet_interaction.first_petting %>
</p>

<p>
  <strong>Last petting:</strong>
  <%= @pet_interaction.last_petting %>
</p>

<%= link_to 'Edit', edit_pet_interaction_path(@pet_interaction) %> |
<%= link_to 'Back', pet_interactions_path %>