config/routes.rb
Rails.application.routes.draw do
  # Sidekiq dashboard
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # Root index
  root 'index#view'
  # Login/logout pages
  devise_for :pets, controllers: { registrations: 'registrations' }
  # Custom redirects and routes
  get '/evelyn' => redirect("http://evelyn.pet")
  get '/naptime' => 'index#naptime'
  get '/pets' => 'index#view'
  # Pettings
  get '/pettings' => 'pet_interactions#index'
  post '/:url/petting'  => 'pet_interactions#do_a_petting'
  get '/:url/pettings' => 'pet_interactions#how_many_pettings'
  # Pet pages
  resources :pages, only: [:edit], param: :url
  # View pet pages at root URL
  resources :pages, path: '', only: [:show, :update], param: :url
end

app/models/petting.rb
class Petting < ApplicationRecord
  belongs_to  :petter,
              class_name: 'Pet',
              inverse_of: :performed_pettings

  belongs_to  :petted,
              class_name: 'Pet',
              inverse_of: :received_pettings
end

app/controllers/pettings_controller.rb
class PettingsController < ApplicationController
  before_action :set_petting, only: [:show, :edit, :update, :destroy]

  # GET /pettings
  # GET /pettings.json
  def index
    @pettings = Petting.where("petter_id=? OR petted_id=?", current_pet.id, current_pet.id)
    @petters = Petting.where("petted_id=?", current_pet.id).group(:petter_id).order('count_id desc').count('id')
    @petted = Petting.where("petter_id=?", current_pet.id).group(:petted_id).order('count_id desc').count('id')
  end

  # GET /pettings/1
  # GET /pettings/1.json
  def show; end

  # GET /pettings/new
  def new
    @petting = Petting.new
  end

  # GET /pettings/1/edit
  def edit; end

  # PATCH/PUT /pettings/1
  # PATCH/PUT /pettings/1.json
  def update
    respond_to do |format|
      if @petting.update(petting_params)
        format.html { redirect_to @petting, notice: 'Petting was successfully updated.' }
        format.json { render :show, status: :ok, location: @petting }
      else
        format.html { render :edit }
        format.json { render json: @petting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pettings/1
  # DELETE /pettings/1.json
  def destroy
    @petting.destroy
    respond_to do |format|
      format.html { redirect_to pettings_url, notice: 'Petting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_petting
    @petting = Petting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def petting_params
    params.require(:petting).permit(:petter_id, :petted_id, :petted_at)
  end
end

app/views/pettings/_form.html.erb
<%= form_for(petting) do |f| %>
  <% if petting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(petting.errors.count, 'error') %> prohibited this petting from being saved:</h2>

      <ul>
      <% petting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :petter_id %>
    <%= f.number_field :petter_id %>
  </div>

  <div class="field">
    <%= f.label :petted_id %>
    <%= f.number_field :petted_id %>
  </div>

  <div class="field">
    <%= f.label :petted_at %>
    <%= f.datetime_select :petted_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pettings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
    <h1>Your petters</h1>

    <ul class="list-group">
      <% @petters.each do |petter| %>
      <li class="list-group-item">
        <% if petter[0] %>
        <% pet = Pet.find(petter[0]) %>
        <%= link_to pet.name, pet.page.url %>
        <% else %>
        Anonymous
        <% end %>
        <span class="badge"><%= petter[1] %></span>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-6">
    <h1>Your petted pets</h1>
    <ul class="list-group">
      <% @petted.each do |petted| %>
      <li class="list-group-item">
        <% pet = Pet.find(petted[0]) %>
        <%= link_to pet.name, pet.page.url %>
        <span class="badge"><%= petted[1] %></span>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pettings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Petter:</strong>
  <%= @petting.petter_id %>
</p>

<p>
  <strong>Petted:</strong>
  <%= @petting.petted_id %>
</p>

<p>
  <strong>Petted at:</strong>
  <%= @petting.petted_at %>
</p>

<%= link_to 'Edit', edit_petting_path(@petting) %> |
<%= link_to 'Back', pettings_path %>