config/routes.rb
Rails.application.routes.draw do
  # Sidekiq dashboard
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # Root index
  root 'index#view'
  # Login/logout pages
  devise_for :pets, controllers: { registrations: 'registrations' }
  # Custom redirects and routes
  get '/evelyn' => redirect("http://evelyn.pet")
  get '/naptime' => 'index#naptime'
  get '/pets' => 'index#view'
  # Pettings
  get '/pettings' => 'pet_interactions#index'
  post '/:url/petting'  => 'pet_interactions#do_a_petting'
  get '/:url/pettings' => 'pet_interactions#how_many_pettings'
  # Pet pages
  resources :pages, only: [:edit], param: :url
  # View pet pages at root URL
  resources :pages, path: '', only: [:show, :update], param: :url
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pleasepet</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <script data-turbolinks-eval="false">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-92262726-1', 'auto');
  </script>
  <script>
    ga('set', 'location', location.href.split('#')[0]);
    ga('send', 'pageview', { "title": document.title });
  </script>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <a class="navbar-left navbar-brand" href="/">
        PleasePet
      </a>
      <ul class="nav navbar-nav navbar-right">
        <% if current_pet %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_pet.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Your pet network", pettings_url %></li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to "Edit pet page", edit_page_url(url: current_pet.page.url) %>
              </li>
              <li><%= link_to "Account settings", edit_registration_path(current_pet) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign out", destroy_session_path(current_pet), method: :delete%></li>
            </ul>
          </li>
        <% else %>
          <li>
            <a href="/pets/sign_up">Sign up</a>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="container">
    <% if notice %>
      <div class="alert alert-info" role="alert"><%= notice %></div>
    <% end %>
    <%= yield %>
  </div>
  <script type="text/javascript">
      window.doorbellOptions = {
          appKey: 'kCkdBHpgW4NotHxKodpV4N1eVX9cfxqYpRVHJpPmKAZIUjODVrLF266AyiyDMZfT'
      };
      (function(w, d, t) {
          var hasLoaded = false;
          function l() { if (hasLoaded) { return; } hasLoaded = true; window.doorbellOptions.windowLoaded = true; var g = d.createElement(t);g.id = 'doorbellScript';g.type = 'text/javascript';g.async = true;g.src = 'https://embed.doorbell.io/button/5747?t='+(new Date().getTime());(d.getElementsByTagName('head')[0]||d.getElementsByTagName('body')[0]).appendChild(g); }
          if (w.attachEvent) { w.attachEvent('onload', l); } else if (w.addEventListener) { w.addEventListener('load', l, false); } else { l(); }
          if (d.readyState == 'complete') { l(); }
      }(window, document, 'script'));
  </script>
</body>
</html>